from keyword import kwlist
o = """ThereareyouIandletlistintgameJupiterlinedefb \
lindasyieldassertbreakclasscontinueexceptfinallyfor \
fromglobalimportnonlocalpassraisereturntrywhilewithandor\
asassertbreakclasscontinuedefdelelifelseexceptexecfinally\
forfromglobalifimportinislambdnonlocalnotorpassprintraisere\
prreturnsupertrywhilewithyieldTrueFalseNoneasyncawaitmatchca\
senonelocaloverrideprivatesealedstaticmethodvolatileabstracte\
numintfloatdoublebyteboolcharstructvectorlistdictionaryqueuest\
ackinterfacenulltrycatchfinallythrowthrowsimplementsextendspubl\
icprotectedprivatefinalstaticvoidmainStringargsSystemoutprintlnn\
ewMapSetGetAddRemoveClearIsEmptySizeContainsKeyContainsValueKeyVa\
luePairsForEachDoWhileSwitchCaseDefaultbreakcontinueiteratoriterab\
lecollectionsframeworksynchronizedtransientvolatilestrictfpbitwisel\
ogicalshiftcompoundassignmenttypeinferencegenericswildcardstypeerasu\
rereflectionproxydecoratorfactorysingletonprototypebuildercompositead\
apterbridgechainofresponsibilitycommandstateobservermementointerpret\
eriteratorvisitorstrategytemplatemethodflyweightmediatorproxymultith\
readingconcurrencyasynchronousprogrammingeventdrivenarchitecturefunc\
tionalprogrammingimmutables...\
quantumcomputingqubitsentanglementsuperpositionquantumalgorithmsShorsGroverquantumcryptographyquantumteleportationartificialintelligenceAIoptimizationalgorithmsgraphtheorytraversalsearchalgorithmsdepthfirstsearchbreadthfirstsearchAstaralgorithmgeneticalgorithmssimulatedannealingparticlewarmoptimizationantcolonyoptimizationmachinelearningdeeplearningunsupervisedlearningreinforcementlearningneuralnetworksconvolutionalneuralnetworksrecurrentneuralnetworkslongshorttermmemorynetworksgenerativeadversar...
blockchaintechnologydistributedledgerconsensusalgorithmsproofOfWorkproofOfStakeByzantineFaultTolerancepeer-to-peerP2PnetworkscryptographyhashfunctionsasymmetricencryptionpublickeyinfrastructurePKIdigitalcertificatesdigital signaturesmartcontractsdecentralizedapplicationsDAppsEthereumplatformSolidityprogramminglanguageWeb3technologyNFTsnon-fungibletokensDeFidecentralizedfinancedecentralizedexchangesDEXsstablecoinscryptocurrencyminingstakingyieldfarmingliquiditypoolsoraclesDAOsdecentralizedautonomousorganizati..."""

li = []
for i in kwlist:
    if i in o:
        li.append(i)

print(li)
print(kwlist == li)